### ISSUE TITLE
Incorrect checksum on master

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/f2c-feedstock#10]
Appears the [builds on `master`]( https://travis-ci.org/conda-forge/f2c-feedstock/jobs/457747981#L433 ) are getting the wrong checksum, which is causing them to fail. Are we still downloading what we expect?

**Comment by Areustle** [comment]
I have updated the source origin and checksum(s) in the meta.yaml. Should be good moving forward.

**Comment by jakirkham** [comment]
Thanks Alex! 🙏
