### ISSUE TITLE
Fixing license metadata to be SPDX compliant

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/f2c-feedstock#17]
Currently the `license` metadata field says `OTHER`

https://github.com/conda-forge/f2c-feedstock/blob/d422b1d34e3aa065ac4a062d9fdc8791b9128317/recipe/meta.yaml#L41

This was likely set a while back before SPDX compliance became a requirement in conda-forge. Since this is not SPDX compliant, this linter has been raising about this ( https://github.com/conda-forge/f2c-feedstock/pull/13#issuecomment-1091015644 ).

If this is some form of already supported SPDX license, would be good to match the appropriate one from [this list]( https://spdx.org/licenses/ ). Otherwise would recommend using `LicenseRef-*` for the appropriate custom license (like as is used [here]( https://github.com/conda-forge/versioneer-feedstock/blob/47ad87a740b89643fb8c5ece60a918606b406cce/recipe/meta.yaml#L35 )).

**Comment by Areustle** [comment]
There don't seem to be any matching SPDX licenses for AT&T or Bell(core/labs) that correspond to [the License file](https://github.com/conda-forge/f2c-feedstock/blob/main/recipe/LICENSE). 

There's a more-recent pair of Lucent Technologies Inc. licenses that seem to be a poor fit.

I propose using  `LicenseRef-AT&T-Bell-Attribution` as attribution and no advertisement using company/personnel names are the only limitations, which is similar to the ` BSD-3-Clause-Attribution` identifier.

**Comment by jakirkham** [comment]
cc @conda-forge/core (in case others have thoughts on how this case should be captured)

**Comment by isuruf** [comment]
SMLNJ is the correct one. https://spdx.org/licenses/SMLNJ.html

**Comment by isuruf** [comment]
Opened https://github.com/spdx/license-list-XML/issues/1441 to clarify a small change.

**Comment by jakirkham** [comment]
Wow that's a good find. 

Thanks for raising that. Also was noticing that diff.
