### ISSUE TITLE
64-bit version faults on windows

### ISSUE THREAD

**Issue by ghost** [conda-forge/f2c-feedstock#2]

**Comment by ghost** [comment]
Culprit is putpcc.c in function `save_argtypes` of `putpcc.c` line 1584 (access violation).

**Comment by giacomov** [comment]
@xoviat the source code of f2c has not been changed for a long time. It is here for convenience, but I am not a developer of it. You can try and post the log of the error and I'll see if I can help you, but I am not a Windows developer... 

As alternative, you can download the stand-alone exe for windows here:

http://www.netlib.org/f2c/mswin/index.html

**Comment by ghost** [comment]
I guess you could call me a windows developer, because I seem to know more about windows than other people. I've provided a patch to fix the problem, but I've spent most of my time attempting to fix the patch so that it is cleanly applied.

**Comment by Areustle** [comment]
Cannot reproduce
